-- Create the devices schema

CREATE SCHEMA devices;

-- Create the devices table in devices
CREATE TABLE devices.devices (
    id         bigint generated by default as identity PRIMARY KEY,
    name       varchar(255),
    location   varchar(255),
    email      varchar(255),
    maxkwh     bigint
);

-- Change the owner of the devices table
ALTER TABLE devices.devices OWNER TO postgres;

-- Insert dummy data into the devices table
INSERT INTO devices.devices (id, name, location, email, maxkwh) VALUES
(1, 'Device A', 'Office 101', 'user1@example.com', 123),
(2, 'Device B', 'Lab 202', 'user2@example.com', 132),
(3, 'Device C', 'Warehouse', 'admin@example.com', 3333),
(4, 'Device D', 'Office 102', 'manager@example.com', 2),
(5, 'Device E', 'Main Lobby', 'guest@example.com', 69);