-- Create the users schema
CREATE SCHEMA users;

-- Create the users table in users
CREATE TABLE users.users (
    id       bigint generated by default as identity PRIMARY KEY,
    admin    boolean NOT NULL,
    email    varchar(255),
    password varchar(255),
    username varchar(255)
);

-- Change the owner of the users table
ALTER TABLE users.users OWNER TO postgres;

-- Insert dummy data into the users table
INSERT INTO users.users (admin, email, password, username) VALUES
(true, 'admin@gmail.com', 'qbtt', 'adminUser'),
(false, 'user1@gmail.com', 'qbtt', 'user1'),
(false, 'user2@gmail.com', 'qbtt', 'user2'),
(true, 'manager@gmail.com', 'qbtt', 'manager'),
(false, 'guest@gmail.com', 'qbtt', 'guest');