# Use Node.js as the base image
FROM node:20.18.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli@18.2.11

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the Angular app will run on
EXPOSE 4200

# Start the Angular application in development mode
CMD ["ng", "serve", "--host", "0.0.0.0"]